### ISSUE TITLE
agent.nodeAddressTypes value should have default explicitly in values.yaml.

### ISSUE THREAD

**Issue by matthewhembree** [vantage-sh/helm-charts#4]
https://github.com/vantage-sh/helm-charts/blob/2097e02f8281722cb71118cf9516eac703353c2f/charts/vantage-kubernetes-agent/values.yaml#L28

It's typically, a helm convention to have the defaults be explicitly placed into the vaules.yaml.

I could easily have made this a PR, but I wanted to open a discussion about what should be the default, since this is a new type of integration.

It seems that `Hostname` is the implied default. I've have mixed success with this.
- Didn't work in my GKE clusters
- Inconsistently worked in my EKS clusters.
  - Not a regional thing.
  - All had the same `Corefile`
  - Some had the EC2 domain suffix in `/etc/resolv.conf` ; some didn't. One host worked without the domain suffix in `/etc/resolv/conf`.

I seem to have success with the value set to `InternalIP` across my entire multi-region, multi-cloud (EKS, GKE) fleet. IMO, this should work universally and that's my reason for lobbying for it as the default. I've set it my `values.yaml` for my parent chart, so I'm good. But I just wanted to see if this proposed change would help others.

I don't think it would affect any clusters with a service mesh or HTTP(S) proxy involved.

Thanks!

**Comment by macb** [comment]
We make use of the resolver from [metrics-server](https://github.com/kubernetes-sigs/metrics-server/blob/master/pkg/utils/address_resolver.go#L72-L76) which has the defaults from [here](https://github.com/kubernetes-sigs/metrics-server/blob/master/pkg/utils/address_resolver.go#L28-L39), so with no value it will fallback to that package's default priority. The main reason I didn't set a default value in the chart was to make debugging after the fact easier since it's quicker to spot if an env var is set on the pod to know if it was configured vs. compare the values it is set to with a default string.

Most of the testing has been in EKS but even then we've had customer EKS clusters which have also needed to be configured which is what lead to the configuration in the first place. Anecdotally `InternalIP` would have also worked in those cases.

Also seems like [prometheus](https://github.com/prometheus/prometheus/blob/main/discovery/kubernetes/node.go#L197-L231) uses `NodeInternalIP` as it's highest priority. So definitely a strong case to have that be the default highest priority.

**Comment by matthewhembree** [comment]
Very informative.

I guess I'll explain how I came to this issue.

I saw the cluster data wasn't showing up in the Vantage console. They were listed in the integrations:kubernetes:manage_connection page. Next step was to go look at the pod logs and I saw the node metrics url was the hostname. Eventually, I ended up at the chart values.yaml.

So thinking of how to improve the experience, if it could be improved..
 - I see the docs were updated. 👍 That might be good enough. It would have reduced my TTR for sure.
 - Maybe it would be good to post back status into the Vantage console?.?. Like a status LED. Red for 0/n nodes. Green for >=1/n nodes. Some nodes can't be scraped because of autoscaling deletion, anything 1 or greater indicates success.
 - Or would it be better to have an init function of the agent to test the `nodeAddressTypes` and select from an priority list. e.g. set `agent.nodeAddressTypes: "auto"`
   - `Priority order` is a bit ambiguous. I presume that means if there's a value for a particular `nodeAddressType` key, then it will be used. Otherwise, the next `nodeAddressType` type in the will be checked for presence of a value.
   - My knee jerk reaction is that `priority order` would mean: if a value is present and the scraper doesn't get a 2xx status code, then try the next `nodeAddressType`.

---

Anyway, thanks for the background. 👍 I'm good closing this.

**Comment by macb** [comment]
Great feedback, appreciate the context.
- We do have plans to export agent metadata periodically to allow us to notify customers when their deployed agents are due for an upgrade.
  - Including scrape data so we can also highlight problematic behavior (ie. consistently high failed scrapes).
- The agent does have a `/metrics` prometheus endpoint available which includes node scrape metrics.
  - We don't currently document that endpoint but should.
- The priority order is a bit confusing. We considered testing all of the available options to find one that works but wanted to do that in a way that wouldnt result in Node * Addresses number of requests every scrape interval if they were all invalid.


We'll likely change the default address order and do some initialization testing to find the best-fit for customer clusters if not otherwise configured.
